name: enlighten

on:
  push:
    branches:
      - master
  schedule:
#    - cron:  '0/10 * * * *'   # every 10 mins
    - cron: '0 2,7,12,13 * * *' # At minute 0 past hour 10, 15, 20, and 21 utc +8

jobs:
  run:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t youtube-scount .
      - uses: nick-invision/retry@v2
        with:
          timeout_minutes: 15
          retry_wait_seconds: 300
          max_attempts: 3
          retry_on: any
          command: docker run -e BILIBILI_COOKIE="${{ secrets.BILIBILI_COOKIE }}" -e REPO="${{ secrets.REPO }}" -e UESRNAME="${{ secrets.UESRNAME }}" -e PASSWORD="${{ secrets.PASSWORD }}" youtube-scount
